# Generated by Django 2.1.2 on 2018-10-20 16:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Broj_porudzbine', models.CharField(max_length=32)),
                ('Ukupno', models.CharField(max_length=32)),
                ('Kolicina', models.CharField(max_length=32)),
                ('Datum_narucivanja', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Prodavnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime', models.CharField(max_length=32)),
                ('Grad', models.CharField(max_length=32)),
                ('Br_telefona', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime', models.CharField(max_length=32)),
                ('Stanje', models.IntegerField(max_length=32)),
                ('Cijena', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='prodaja',
            name='Prodavnica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sajt.Prodavnica'),
        ),
        migrations.AddField(
            model_name='prodaja',
            name='Proizvod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sajt.Proizvod'),
        ),
    ]
