# Generated by Django 2.1.2 on 2018-10-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sajt', '0002_auto_20181020_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodaja',
            options={'verbose_name_plural': 'Prodaja'},
        ),
        migrations.AlterModelOptions(
            name='prodavnica',
            options={'verbose_name_plural': 'Prodavnica'},
        ),
        migrations.AlterModelOptions(
            name='proizvod',
            options={'verbose_name_plural': 'Proizvod'},
        ),
    ]
