# Generated by Django 2.1.2 on 2018-10-21 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sajt', '0003_auto_20181021_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodaja',
            name='Ukupno',
        ),
        migrations.AddField(
            model_name='prodaja',
            name='Cijena',
            field=models.DecimalField(decimal_places=5, default=3, max_digits=10000, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sajt.Proizvod')),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prodaja',
            name='Kolicina',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proizvod',
            name='Cijena',
            field=models.DecimalField(decimal_places=5, max_digits=10000),
        ),
    ]
