# Generated by Django 2.1.2 on 2018-10-21 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sajt', '0004_auto_20181021_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodaja',
            name='Cijena',
            field=models.DecimalField(decimal_places=2, max_digits=1000, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sajt.Proizvod')),
        ),
        migrations.AlterField(
            model_name='proizvod',
            name='Cijena',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
