# Generated by Django 2.1.2 on 2018-10-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sajt', '0005_auto_20181021_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodaja',
            name='Cijena',
        ),
    ]
