# Generated by Django 2.1.2 on 2018-10-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sajt', '0007_auto_20181021_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodaja',
            name='Cijena',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=1000),
            preserve_default=False,
        ),
    ]
