# Generated by Django 2.1.2 on 2018-10-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sajt', '0008_prodaja_cijena'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodaja',
            options={},
        ),
        migrations.AddField(
            model_name='prodaja',
            name='Ukupno',
            field=models.CharField(blank=True, default='0', editable=False, max_length=20),
        ),
    ]
