# Generated by Django 2.1.2 on 2018-10-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sajt', '0009_auto_20181021_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodaja',
            name='Ukupno',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
