# Generated by Django 2.1.2 on 2018-10-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sajt', '0010_auto_20181021_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodaja',
            options={'verbose_name_plural': 'Prodaja'},
        ),
        migrations.RemoveField(
            model_name='prodaja',
            name='Proizvod',
        ),
        migrations.AddField(
            model_name='prodaja',
            name='Proizvod',
            field=models.ManyToManyField(to='sajt.Proizvod'),
        ),
    ]
