# Generated by Django 2.1.2 on 2018-10-21 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sajt', '0011_auto_20181021_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodaja',
            name='Proizvod',
        ),
        migrations.AddField(
            model_name='prodaja',
            name='Proizvod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sajt.Proizvod'),
        ),
    ]
