# Generated by Django 2.1.2 on 2018-10-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sajt', '0012_auto_20181021_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodaja',
            name='Velicina',
            field=models.CharField(choices=[('S', 'Male'), ('M', 'Srednje'), ('L', 'Velike')], max_length=1, null=True),
        ),
    ]
