# Generated by Django 2.1.2 on 2018-11-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sajt', '0014_blog_galerija_profile_vijesti'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Blog'},
        ),
        migrations.AlterModelOptions(
            name='galerija',
            options={'verbose_name_plural': 'Galerija'},
        ),
        migrations.AlterModelOptions(
            name='vijesti',
            options={'verbose_name_plural': 'Vijesti'},
        ),
        migrations.RemoveField(
            model_name='prodaja',
            name='Proizvod',
        ),
        migrations.AddField(
            model_name='prodaja',
            name='Proizvod',
            field=models.ManyToManyField(to='sajt.Proizvod'),
        ),
    ]
