# Generated by Django 2.1.2 on 2018-11-07 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sajt', '0016_auto_20181107_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porudzbina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_p', models.CharField(max_length=32)),
                ('zaduzeno', models.IntegerField(max_length=32)),
                ('prodato', models.IntegerField(max_length=32)),
                ('stanje', models.CharField(max_length=32)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sajt.Proizvod')),
                ('prodavnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sajt.Prodavnica')),
            ],
        ),
        migrations.AlterField(
            model_name='prodaja',
            name='Prodavnica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
