# Generated by Django 2.1.2 on 2018-11-07 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sajt', '0017_auto_20181107_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porudzbina',
            name='prodato',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='porudzbina',
            name='prodavnica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
