# Generated by Django 2.1.2 on 2018-11-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sajt', '0018_auto_20181107_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porudzbina',
            name='zaduzeno',
            field=models.IntegerField(),
        ),
    ]
